<?php
/**
 * Copyright Spletni sistemi, (c) 2009.
 *
 * This program is free software. You are allowed to use the software but NOT allowed to modify the software.
 * It is also not legal to do any changes to the software and distribute it in your own name / brand.
 *
 * @category   Spletnisistemi
 * @package    Spletnisistemi_Bankart
 * @copyright  Copyright (c) 2009 Spletni sistemi (http://spletnisistemi.si)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <?php if ($this->getMethod()->getCustomText()): ?>
                <?php echo $this->getMethod()->getCustomText() ?><br/>
            <?php endif; ?>
        </div>
    </li>
</ul>
